(function(){
'use strict';
const ENDPOINT='https://dliycybiocnhvqilbrlj.supabase.co/functions/v1/jaguarrt';
const TOKEN_KEY='jaguarrt-session';
const KEYS=['jaguar-rtav-study-progress-v1','jaguar-rtav-quiz-history-v2','jaguar-rtav-quiz-session-v3'];
let token=sessionStorage.getItem(TOKEN_KEY)||'',me=null,loaded=false,timer,attemptQueue=[],saveChain=Promise.resolve();
const by=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}};
async function api(action,data,extra={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,data,...extra})});const x=await r.json();if(!r.ok||x.error)throw Error(x.error||'Não foi possível conectar.');return x;}
function status(text){by('accountStatus').textContent=text;}
function clearLocal(){KEYS.forEach(k=>localStorage.removeItem(k));quizSession=null;}
function hydrate(state){clearLocal();if(state.study)localStorage.setItem(KEYS[0],JSON.stringify(state.study));if(state.history)localStorage.setItem(KEYS[1],JSON.stringify(state.history));if(state.quiz)localStorage.setItem(KEYS[2],JSON.stringify(state.quiz));quizSession=read(KEYS[2],null);renderModuleGrid();updateQuizStats();updateQuizResume();renderHomeResume();go('home');}
function snapshot(){return {study:read(KEYS[0],{}),history:read(KEYS[1],{}),quiz:read(KEYS[2],null)};}
function schedule(){if(!loaded)return;clearTimeout(timer);timer=setTimeout(()=>flush(),600);}
async function flush(){if(!loaded)return;const data=snapshot();saveChain=saveChain.catch(()=>{}).then(async()=>{try{for(const attempt of [...attemptQueue]){await api('attempt',attempt);attemptQueue=attemptQueue.filter(x=>x.id!==attempt.id);sessionStorage.setItem('jaguarrt-pending:'+me.email,JSON.stringify(attemptQueue));}me=await api('save',data);status('Progresso salvo');render();}catch(e){status(e.message+' · alterações aguardando sincronização');}});return saveChain;}
window.JaguarAccount={changed:schedule,attempt(s){if(!loaded)return;attemptQueue.push({id:crypto.randomUUID(),scope:s.scope,questions:s.questions.map(q=>({id:q.id,options:q.options})),answers:s.answers});sessionStorage.setItem('jaguarrt-pending:'+me.email,JSON.stringify(attemptQueue));schedule();}};
function date(v){return v?new Date(v).toLocaleString('pt-BR'):'—';}
function progress(state){let read=0,total=0,done=0;for(const m of STUDY_MODULES){const steps=new Set((state?.study?.[m.id]?.read||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<m.blocks.length));read+=steps.size;total+=m.blocks.length;if(steps.size===m.blocks.length)done++;}return {pct:total?Math.round(read/total*100):0,done};}
function attemptsHtml(attempts){return attempts.length?attempts.slice(0,30).map(a=>`<li><span>${esc(a.scope==='all'?'Todos os módulos':'Módulo '+a.scope)}<small>${date(a.created_at)}</small></span><b>${a.score}/10</b></li>`).join(''):'<li>Nenhum teste finalizado.</li>';}
function render(){if(!me)return;by('accountEmail').textContent=me.email;const p=progress(me.state);by('accountContent').innerHTML=`<div class="account-summary"><strong>${p.pct}%</strong><span>do percurso estudado<small>${p.done} de ${STUDY_MODULES.length} módulos concluídos</small></span></div><progress max="100" value="${p.pct}"></progress><h3>Seus módulos</h3><ul class="account-list">${STUDY_MODULES.map(m=>{const n=new Set(me.state?.study?.[m.id]?.read||[]).size;return `<li><span>${esc(m.title)}</span><b>${n}/${m.blocks.length}</b></li>`;}).join('')}</ul><h3>Resultados dos testes</h3><ul class="account-list">${attemptsHtml(me.attempts||[])}</ul><small>O progresso anterior deste navegador não é atribuído automaticamente a uma conta.</small>`;by('adminSection').hidden=me.email!=='rodrigo.silva@jaguarcontabil.com.br';by('adminLoad').hidden=!me.admin;by('adminVerify').hidden=!!me.admin;}
async function enter(x){token=x.token||token;sessionStorage.setItem(TOKEN_KEY,token);me=x;const proof=sessionStorage.getItem('jaguarrt-admin-proof');if(proof){sessionStorage.removeItem('jaguarrt-admin-proof');try{me=await api('verify_admin',null,{access_token:proof});}catch(e){by('loginError').textContent=e.message;}}hydrate(me.state||{});attemptQueue=JSON.parse(sessionStorage.getItem('jaguarrt-pending:'+me.email)||'[]');loaded=true;by('loginGate').hidden=true;by('siteShell').inert=false;by('siteShell').hidden=false;by('accountToggle').hidden=false;render();status('Progresso sincronizado');}
by('loginForm').addEventListener('submit',async e=>{e.preventDefault();const button=by('loginSubmit');button.disabled=true;by('loginError').textContent='Entrando…';try{const x=await api('login',null,{email:by('loginEmail').value.trim(),password:by('loginPassword').value});by('loginPassword').value='';await enter(x);by('loginError').textContent='';}catch(e){by('loginError').textContent=e.message;}finally{button.disabled=false;}});
let priorFocus;
function close(){by('accountDrawer').hidden=true;by('accountBackdrop').hidden=true;by('accountToggle').setAttribute('aria-expanded','false');priorFocus?.focus();}
by('accountToggle').onclick=async()=>{priorFocus=document.activeElement;by('accountDrawer').hidden=false;by('accountBackdrop').hidden=false;by('accountToggle').setAttribute('aria-expanded','true');by('accountClose').focus();await flush();};
by('accountClose').onclick=close;by('accountBackdrop').onclick=close;
by('accountDrawer').addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...by('accountDrawer').querySelectorAll('button,input,a')].filter(x=>!x.hidden&&x.offsetParent);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus();}}});
by('accountLogout').onclick=async()=>{await flush();try{await api('logout');}catch{status('Não foi possível encerrar no servidor. Tente novamente.');return;}loaded=false;token='';me=null;attemptQueue=[];sessionStorage.removeItem(TOKEN_KEY);clearLocal();close();by('accountToggle').hidden=true;by('siteShell').hidden=true;by('siteShell').inert=true;by('loginGate').hidden=false;by('loginEmail').focus();};
by('adminVerify').onclick=async()=>{by('adminMessage').textContent='Enviando confirmação…';try{await api('send_admin');by('adminMessage').textContent='Abra o link recebido no e-mail para liberar o painel. Se não retornar ao site, use a configuração de redirecionamento do Supabase.';}catch(e){by('adminMessage').textContent=e.message;}};
by('adminLoad').onclick=async()=>{by('adminMessage').textContent='Carregando…';try{const x=await api('admin');by('adminMessage').textContent=x.accounts.length+' colaboradores · ativo = sessão nos últimos 2 minutos';by('adminContent').innerHTML=x.accounts.map(a=>{const p=progress(a.state);return `<details class="account-person"><summary><b>${esc(a.email)}</b><span>${a.online?'● Ativo recentemente':'Offline'} · ${p.pct}%</span></summary><p>Último acesso: ${date(a.last_seen)}<br>${p.done} módulos concluídos</p><ul class="account-list">${STUDY_MODULES.map(m=>`<li><span>${esc(m.title)}</span><b>${new Set(a.state?.study?.[m.id]?.read||[]).size}/${m.blocks.length}</b></li>`).join('')}</ul><h4>Testes</h4><ul class="account-list">${attemptsHtml(a.attempts||[])}</ul></details>`;}).join('');}catch(e){by('adminMessage').textContent=e.message;}};
setInterval(async()=>{if(!loaded||document.hidden)return;try{if(attemptQueue.length){await flush();return;}me=await api('state');render();}catch(e){status(e.message);}},60000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&loaded)flush();});
(async()=>{by('siteShell').inert=true;by('siteShell').hidden=true;try{if(token)await enter(await api('state'));const hash=new URLSearchParams(location.hash.slice(1));const access=hash.get('access_token');if(access){history.replaceState(null,'',location.pathname+location.search);if(loaded){me=await api('verify_admin',null,{access_token:access});render();status('Administrador confirmado');}else {sessionStorage.setItem('jaguarrt-admin-proof',access);by('loginError').textContent='E-mail confirmado. Entre para abrir o painel administrativo.';}}}catch(e){token='';sessionStorage.removeItem(TOKEN_KEY);by('loginError').textContent=e.message;}})();
})();
